############################################################
## GTA:World Config
############################################################

# Complete page title
title: Los Santos Fire Department - Statewide PIO Scanner

# Language config
languageCode: en

############################################################
## More default config. in /config/_default/config.yml
############################################################


############################################################
## Status default config. Valid for ALL languages.
############################################################

params:
  systems:
    - name: North Los Santos
      description: "Areas of Vinewood, Vinewood Hills, Rockford Hills, Richman,
      Backlot City and Morningwood. (Area Codes; 323, 700)"
    - name: East Los Santos
      description: "Areas of South Los Santos including the districts of 
      La Mesa, Murrieta Oil Field, Mirror Park. (Area Codes; 730)"
    - name: Central Los Santos
      description: "Areas of Downtown Los Santos. (Area Codes; 560)"
    - name: South Los Santos
      description: "Areas of South Los Santos, La Puerta, Port of Los Santos,
      LISA. (Area Codes; 562, 216)"
    - name: West Los Santos
      description: "Areas of Vespucci, Del Perro, Little Seoul, Pacific Bluffs.
      (Area Codes; 424)"
    - name: Blaine County
      description: "Areas of Blaine County including the districts of Sandy
      Shores and Paleto Bay. (Area Codes; 999, 805)"
  # dateFormat Default: "January 2, 2006 at 3:04 PM"
  # shortDateFormat Default: "15:04 — Jan 2"
  dateFormat: "January 2, 2006 at 3:04 PM"
  shortDateFormat: "15:04 — Jan 2"
  # This string will be displayed after each time displayed
  # Set it for instance to " UTC" to indicate UTC times
  # or a specific time zone, ie " America/New_York"
  # You can also instead used a translated string per language
  timezoneString: " UTC"

  # Path to logo image from the /static folder.
  logo: "/images/logo.png"

  # favicon
  icon: "/images/favicon.png"
  iconType: "image/png"

  # Descriptions
  meta_description: "This page provides information updated by the LSFD Public Relations Department about incidents that may be happening in the city."
  description_footer: "This website was created using a framework called clearstatus, view the source code of the website <a class='text-grey-darkest' href='https://github.com/biscuitgtaw/clearstatus' >here</a>."
  description_header: "Information about the <a class='text-grey-darkest' title='Los Santos Fire Department' href='https://lsfd.gta.world/'>Los Santos Fire Department</a> and their operations.<br />Follow us <a class='text-grey-darkest' title='Visit our page on Facebrower' href='https://face.gta.world/pages/LSFire'>on Facebrowser</a> for more detailed information about our incidents.<br/><a class='text-grey-darkest' href='%s' >Subscribe via RSS</a>"

  copyrightHolder: "LSFD.Live"

  # Disqus commenting per issue: set your Disqus shortname here
  # Leave empty for no discussion at all.
  # You can also enable/disable discussions per issue
  disqusShortname: lsfd

  # Layout
  eventsPerPage: 10

############################################################
## More default config. in /config/_default/params.yml
############################################################